print("="*100)
print("Bem vindo ao programa de gereciamento de contas bancárias!!!")
print("="*100)
print("O que deseja fazer???\n1-Visualizar clientes cadastrados \n2-Cadastrar/Editar clientes")
print("3-Acessar uma conta \n4-Encerrar uma conta \n5-Sair")
input("Digite sua opção: ")